delete:
   description: Deletes a product by id
   operationId: deleteProduct
   parameters:
   -  name: id #should be name
      description: the id of the product to delete from the database
      in: path
      required: true
      schema:
         type: integer
         format: int64
   responses:
      '200':
         description: OK
   tags:
   - product