get:
   description: Returns a list of products
   operationId: listProducts
   responses:
      '200':
         description: successful operation
         content:
            application/json:
               schema:
                  type: array
                  properties: null
                  items:
                     $ref: ../components/product.yaml
   tags:
   - product
post:
   operationId: addProduct
   requestBody:
      required: true
      content:
         application/json:
            schema:
               $ref: ../components/product.yaml
   responses:
      '200':
         description: Successfully added a Product
      '400':
         description: Invalid Product request
         content:
            application/json:
               schema:
                  type: object
                  properties:
                     message:
                        type: string
   tags:
   - product