openapi: 3.0.3
info:
   description: Documentation for Product API
   title: of Product API
   version: 1.0.1

components:
   schemas:
      $ref: ./components/_index.yaml
paths:

# https://github.com/dgarcia360/openapi-boilerplate/blob/master/src/openapi.yaml
   /products:
      $ref: ./paths/products.yaml
   /products/{id}:
      $ref: ./paths/productDelete.yaml